### ISSUE TITLE
Lots of stuff got replaced or messed up on our server

### ISSUE THREAD

**Issue by WickedSchnitzel** [gabriella-campos-davis/Herbarium#8] opened 2024-05-14 19:41 UTC
after updating Herbarium and Wildcraft Fruits and Nuts to the newest version.
Backpacks, Helve Hammers, Tabletop pieces etc got replaced with lemons, bush clippings and whatnot.

Remapping options are not available.

**Comment by WickedSchnitzel** [comment] 2024-05-14 19:52
![Desktop Screenshot 2024 05 14 - 21 50 47 54](https://github.com/gabriella-campos-davis/Herbarium/assets/61825560/d65d3b98-4482-46ec-83fc-d39d25b30146)

**Comment by gabriella-campos-davis** [comment] 2024-05-15 03:23
Hey it looks like you server has had a lot of weird and not reproducible bugs relating to Wildcraft. Can I get a full mod list, for your server? It'd also be very helpful to know a full version history and mod version history for your world. I'm going to mark your other issue as closed and we can focus your various server issues here.

**Comment by WickedSchnitzel** [comment] 2024-05-15 05:20
![Desktop Screenshot 2024 05 15 - 07 18 24 07](https://github.com/gabriella-campos-davis/Herbarium/assets/61825560/dc4cb445-e436-4d1f-b545-b453331023b1)
![Desktop Screenshot 2024 05 15 - 07 17 54 40](https://github.com/gabriella-campos-davis/Herbarium/assets/61825560/ebf078f0-390a-4211-8d45-8f6832299b3c)
![Desktop Screenshot 2024 05 15 - 07 18 13 59](https://github.com/gabriella-campos-davis/Herbarium/assets/61825560/2bbede6a-6174-456f-9a5f-0ef5b4cde6f1)

**Comment by WickedSchnitzel** [comment] 2024-05-15 05:21
The current world is around 3 months old.

**Comment by WickedSchnitzel** [comment] 2024-05-15 05:23
I think we have updated to 1.19.7 after beginning the current world.

**Comment by WickedSchnitzel** [comment] 2024-05-15 05:23
I believe these problems could be resolved through remapping?

**Comment by gabriella-campos-davis** [comment] 2024-05-15 17:51
You could try remappings, but make sure to backup your world beforehand, because i'm not sure if they'd work. Worth a shot though.

I have no idea what would cause this though. Sorry you're dealing with this. We haven't done anything that would corrupt worlds like this, so i'm not sure this is an issue with the mod. What do your server specific mods do?

something you could check (which i don't know if servers have or how that works). in VintagestoryData, there is the Cache > unpack folder with unpacked mods. sometimes old versions get stuck there and cause issues. this is probably not the issue for you all, but it might be worth looking at. (typically, when someone has weird unreproducible bugs, i tell people to look there, so it might be worth a look).

Otherwise i'm not really sure how to help you all.

**Comment by RogueRaiden** [comment] 2024-05-17 10:57
[](https://www.vintagestory.at/blog.html/news/v1198-dot-the-is-and-cross-the-ts-r386/)
![image](https://github.com/gabriella-campos-davis/Herbarium/assets/26943867/303485e0-f8b5-4f81-b64d-585355cff605)

**Comment by gabriella-campos-davis** [comment] 2024-05-17 16:18
Yeah, looks like this was caused by having a lot of modded items. Since it seems like it was a base game issue, i'm going to mark this as closed, as it's hopefully fixed now.

**Closed by gabriella-campos-davis** 2024-05-17 16:18 UTC
Labels: base game issue
